server:
    port: 80

spring:
    application:
        name: cloud-order-service
    # sleuth
    zipkin:
        base-url: http://81.68.76.155:9411
    sleuth:
        sampler:
            # 采样率介于0-1之间,1表示全部收集
            probability: 1
eureka:
    client:
        # 是否注册eureka
        register-with-eureka: true
        # 这里集群必须为true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
        instance-id: order80
        prefer-ip-address: true