server:
    port: 9527

spring:
    application:
        name: cloud-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
            routes:
                -   id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
                    #uri: http://localhost:8001          #匹配后提供服务的路由地址
                    uri: lb://cloud-payment-service #匹配后提供服务的路由地址(ib:负载均衡阿缩写)
                    predicates:
                        - Path=/payment/get/**         # 断言，路径相匹配的进行路由

                -   id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
                    #uri: http://localhost:8001          #匹配后提供服务的路由地址
                    uri: lb://cloud-payment-service #匹配后提供服务的路由地址
                    predicates:
                        - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
                        - After=2020-07-11T23:11:39.607+08:00[GMT+08:00]      #在这个时间之后才能访问,可以通过ZonedDateTime.now();生成此格式
                        - Before=2022-07-11T23:11:39.607+08:00[GMT+08:00]      #在这个时间之后才能访问,可以通过ZonedDateTime.now();生成此格式
                        - Between=2020-07-11T23:11:39.607+08:00[GMT+08:00],2022-07-11T23:11:39.607+08:00[GMT+08:00]      #在这个时间之后才能访问,可以通过ZonedDateTime.now();生成此格式
                        # - Cookie=username,zhangsan    #请求cookie必须带有key=username,value=zhangsan;格式 - Cookie=属性名,正则表达式
                        # - Header=X-Request-Id,\d+    #请求头要含有X-Request-Id属性,且值必须满足\d+ => 整数
                        - Method=GET
                        # - Query=username,\d+      # 属性名,条件
                        # filters:
                        # - AddRequestParameter=X-Request-Id,1024   #过滤器工程会在匹配的请求头上加一对请求头,名称为X-Request-Id,值为1024
eureka:
    instance:
        hostname: cloud-gateway-service
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka