server:
    port: 8803
spring:
    application:
        name: cloud-stream-consumer
    cloud:
        stream:
            bindings: #服务的整合处理
                input: #通道的名称
                    destination: studyExchange #使用StudyExchange名称定义
                    content-type: application/json  #设置消息类型,本次为json,文本设置为"text/plain)
                    group: toolmanclubA
            default-binder: rabbit
    rabbitmq:
        host: 81.68.76.155
        port: 5672
        username: guest
        password: guest


eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka
    instance:
        lease-expiration-duration-in-seconds: 5
        lease-renewal-interval-in-seconds: 2
        instance-id: receive-8803.com
        prefer-ip-address: true