server:
    port: 7001

eureka:
    instance:
        hostname: eureka7001.com
    client:
        # false 表示不在注册中心注册自己
        register-with-eureka: false
        # false 表示自己就是注册中心,职责是维护服务实例,不需要区域检索服务,集群状态下需要开启
        fetch-registry: true
        service-url:
            # 集群版
            defaultZone: http://eureka7002.com:7002/eureka
            # 单机版
            # defaultZone: http://eureka7001.com:7001/eureka
        # server:
        # 禁用自我保护机制
        # enable-self-preservation: false
        # 监控心跳时间(单位/s)
        # eviction-interval-timer-in-ms: 2000