server:
    port: 8801
spring:
    application:
        name: cloud-stream-provider
    cloud:
        stream:
            bindings:
                output:
                    destination: studyExchange
                    content-type: application/json
    rabbitmq:
        host: 81.68.76.155
        port: 5672
        username: guest
        password: guest

eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka
    instance:
        lease-expiration-duration-in-seconds: 5
        lease-renewal-interval-in-seconds: 2
        instance-id: send-8801.com
        prefer-ip-address: true