server:
    port: 80
spring:
    application:
        name: feign-comuser-order
eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
    level:
        com.toolmanclub.springcloud.service.PaymentFeignService: debug
## 设置feign客户端超时时间(默认支持ribbon)
#ribbon:
#    # 指建立连接后从服务器读取到可用资源所用的时间
#    ReadTimeout: 5000
#    # 指建立连接所用的事件,适用于网络状况正常的情况下,两端连接所需要的事件
#    ConnectTimeout: 5000