server:
    port: 8401
spring:
    application:
        name: cloud-alibaba-sentinel-service
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
        sentinel:
            transport:
                # dashboard地址
                dashboard: localhost:8888
                # 默认8719端口,如果占用会自动从8719开始一次扫描+1,直至未被占用的端口
                port: 8719

management:
    endpoints:
        web:
            exposure:
                include: "*"

feign:
    sentinel:
        enabled: true # 激活Sentinel对Feign的支持